import "./globals.css";
import Link from "next/link";
import NavLink from "./components/NavLink";
import Footer from "./components/Footer";

export const metadata = {
  title: "Indian Audit and Accounts Department, Karnataka Reports",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <div className="absolute z-0 inset-0 overflow-hidden">
            <div className="circle-one blur-3xl w-64 h-64 rounded-full bg-rose-400/60 top-0 right-28 absolute"></div>
            <div className="circle-two blur-3xl w-64 h-64 rounded-full bg-indigo-400/60 bottom-0 left-28 absolute"></div>
          </div>
          <header className="bg-white/50 backdrop-blur z-10">
            <div className="max-w-4xl mx-auto flex items-center justify-between">
              <h2 className="text-2xl text-gray-700 py-6">Indian Audit and Accounts Department Karnataka Reports</h2>
              <nav>
                <ul className="flex gap-x-1 text-gray-800 text-sm">
                  <li>
                    <NavLink text="Home" path="/" />
                  </li>
                  <li>
                    <NavLink text="Our Reports" path="/our-reports" />
                  </li>
                  <li>
                    <NavLink text="About Us" path="/about-us" />
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          <main className="backdrop-blur  max-w-6xl mx-auto bg-white/60 rounded-xl py-7 px-8 m-6 ">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
