import '../../globals.css'; // Adjusted path to the global CSS file
import Link from "next/link";
import NavLink from "@/app/components/NavLink"; // Corrected path to NavLink component
import Footer from "@/app/components/Footer"; // Corrected path to Footer component
import LanguageSwitcher from "@/app/components/language-switcher"; // Corrected path to LanguageSwitcher component

export const metadata = {
  title: "IAAD, Karnataka Reports",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params; 
  return (
    <html lang={locale}>
      <head>
        {/* Add any meta tags or links here */}
      </head>
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <div className="absolute z-0 inset-0 overflow-hidden">
            <div className="circle-one blur-3xl w-64 h-64 rounded-full bg-rose-400/60 top-0 right-28 absolute"></div>
            <div className="circle-two blur-3xl w-64 h-64 rounded-full bg-indigo-400/60 bottom-0 left-28 absolute"></div>
          </div>
          {/* Language Switcher in the Top-Right Corner */}
          <div className="absolute top-4 right-4 z-50">
            <LanguageSwitcher currentLocale={locale} />
          </div>
          <header className="bg-white/50 backdrop-blur z-10">
            <div className="max-w-4xl mx-auto flex items-center justify-between">
              <h2 className="text-xl text-gray-700 py-3">
                IAAD Karnataka Reports
              </h2>
              <nav className="flex items-center gap-x-4">
                <ul className="flex gap-x-1 text-gray-800 text-sm">
                  <li>
                    <NavLink text="Home" path={`/${locale}/`} />
                  </li>
                  <li>
                    <NavLink text="Our Reports" path={`/${locale}/our-reports`} />
                  </li>
                  <li>
                    <NavLink text="About Us" path={`/${locale}/about-us`} />
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          <main className="backdrop-blur max-w-6xl min-h-fit mx-auto bg-white/60 rounded-xl py-7 px-8 ">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}