import '../../globals.css';
import NavLink from "@/app/components/NavLink";
import Footer from "@/app/components/Footer";
import LanguageSwitcher from "@/app/components/language-switcher";


export const metadata = {
  title: "IAAD, Karnataka Reports",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params; 
  return (
    <html lang={locale}>
      <head>
        {/* Add any meta tags or links here */}
      </head>
      <body>
        <div className="bg-white min-h-screen flex flex-col">
          {/* <div className="fixed z-0 inset-0 overflow-hidden">
            <div className="circle-one blur-3xl w-64 h-64 rounded-full bg-rose-400/60 top-0 right-28 absolute"></div>
            <div className="circle-two blur-3xl w-64 h-64 rounded-full bg-indigo-400/60 bottom-0 left-28 absolute"></div>
          </div> */}
          <header className="fixed top-0 left-0 w-full z-30 bg-white/70 backdrop-blur border-b border-gray-200 md:ml-64">
            <div className="max-w-4xl mx-auto flex flex-col px-6 md:px-10 py-2">
              <div className="flex justify-end mb-2">
                <LanguageSwitcher currentLocale={locale} />
              </div>
              <div className="flex items-center justify-between">
                <h2 className="text-xl text-gray-700 bottom-4">
                  SFAR Karnataka Report
                </h2>
                <nav className="flex items-center gap-x-4">
                  <ul className="flex gap-x-1 text-gray-800 text-sm">
                    <li>
                      <NavLink text="DashBoard" path={`/${locale}/`} />
                    </li>
                    <li>
                      <NavLink text="Our Reports" path={`/${locale}/our-reports`} />
                    </li>
                    <li>
                      <NavLink text="About Us" path={`/${locale}/about-us`} />
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </header>
          <main className="flex-1 min-h-0 flex flex-col mt-[64px]">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}